# Generated by Django 5.0.7 on 2024-07-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default=-33, max_length=255),
        ),
    ]
